stages:
  - check
  - test
  - build

.node_before: &node_before
  - node -v
  - npm -v
  # NOTE: --unsafe-perm is required for patches
  # SOURCE: https://github.com/ds300/patch-package/issues/185
  - npm ci --cache "$CI_PROJECT_DIR/.npm" --prefer-offline --unsafe-perm

.node_cache: &node_cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
  policy: pull

.check_template:
  stage: check
  image: node:18.20-alpine
  before_script:
    - *node_before
  cache:
    - *node_cache


lint_check:
  extends: 
    - .check_template
  script:
    - npm run lint


ts_check:
  extends: 
    - .check_template
  script:
    - npm run tsc


test_check:
  extends: 
    - .check_template
  script:
    - npm run test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml

build_android_apk:
  image: reactnativecommunity/react-native-android:latest
  stage: build
  before_script:
    - *node_before
  script:
    - cd android
    - ./gradlew clean
    - ./gradlew assembleRelease
  cache:
    paths:
      - node_modules/
  artifacts:
    name: app-release
    paths:
      - app-release.apk
    expire_in: 1 week
