image: node:18.20-alpine

stages:
    - test
    - check

before_script:
    - npm ci

cache:
    paths:
        - node_modules/

lint_check:
    stage: check
    script:
        - npm run lint

ts_check:
    stage: check
    script:
        - npm run tsc


test_check:
    stage: test
    before_script:
        - npm install --save-dev jest-junit
    script:
        - jest --ci --reporters=default --reporters=jest-junit
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml
