stages:
  - check
  - test
  - build

.node_before: &node_before
  - node -v
  - npm -v
  # NOTE: --unsafe-perm is required for patches
  # SOURCE: https://github.com/ds300/patch-package/issues/185
  - npm ci --cache "$CI_PROJECT_DIR/.npm" --prefer-offline --unsafe-perm

.node_cache: &node_cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
  policy: pull

.check_template:
  stage: check
  image: node:18.20-alpine
  before_script:
    - *node_before
  cache:
    - *node_cache

.develop_check_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual
    - if: '$CI_COMMIT_BRANCH != "develop"'
      when: always

.build_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_COMMIT_BRANCH == "stage"
      when: always

lint_check:
  extends:
    - .check_template
    - .develop_check_rules
  script:
    - npm run lint
  

ts_check:
  extends:
    - .check_template
    - .develop_check_rules
  script:
    - npm run tsc

test_check:
  extends:
    - .check_template
    - .develop_check_rules
  script:
    - npm run test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml

build_android_apk:
  image: reactnativecommunity/react-native-android:latest
  variables:
    SECURE_FILES_DOWNLOAD_PATH: '.secure_files/'
  stage: build
  extends:
    - .build_rules
  before_script:
    - *node_before
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp .secure_files/signing.properties android/
    - cp .secure_files/my-upload-key.keystore android/app/
    - cd android
    - ./gradlew clean
    - ./gradlew assembleRelease
    - cd ..
    - cp android/app/build/outputs/apk/release/app-release.apk app-release.apk
  cache:
    paths:
      - node_modules/
  artifacts:
    name: app-release
    paths:
      - app-release.apk
    expire_in: 1 week
