image: node:18.20-alpine  # Define the image here for all jobs

stages:
  - check
  - test
  - build

cache:
  paths:
    - node_modules/

lint_check:
  stage: check
  before_script:
    - npm ci
  script:
    - npm run lint

ts_check:
  image: node:18.20-alpine
  stage: check
  before_script:
    - npm ci
  script:
    - npm run tsc


test_check:
  image: node:18.20-alpine
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml

build_android_apk:
  image: reactnativecommunity/react-native-android:latest
  stage: build
  script:
    - npm ci
    - cd android
    - ./gradlew clean
    - ./gradlew assembleRelease
  cache:
    paths:
      - node_modules/
  artifacts:
    name: app-release.apk
    paths:
      - build/android/app/build/outputs/apk/release/app-release.apk
    expire_in: 1 week
