name: React Native CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  install_dependency:
    runs-on: ubuntu-latest
    container: node:18.20-alpine
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
      - run: npm ci

  check_eslint:
    name: "Check eslint"
    runs-on: ubuntu-latest
    needs: install_dependency
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
      - run: npm ci --prefer-offline
      - run: npm run lint

  check_tslint:
    name: "Check tslint"
    runs-on: ubuntu-latest
    needs: install_dependency
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
      - run: npm ci --prefer-offline
      - run: npm run tsc

  check_tests:
    name: "Check tests"
    runs-on: ubuntu-latest
    needs: [check_eslint, check_tslint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
      - run: npm ci --prefer-offline
      - run: npm run test
      - name: Upload Jest JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: junit.xml
      - name: Upload Jest Cobertura report
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-report
          path: coverage/cobertura-coverage.xml

  build_android_apk:
    name: "Build android apk"
    runs-on: ubuntu-latest
    needs: check_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
      - run: npm ci --prefer-offline
      - name: "Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: "Build apk"
        run: "cd android && ./gradlew assembleRelease"
      - name: "Upload apk"
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
